In [1]:
import torch
a = torch.ones(3)

In [2]:
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
a[2] = 2.0

In [6]:
a

tensor([1., 1., 2.])

In [7]:
points = torch.ones(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [8]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
pt = list(points)

In [10]:
pt

[tensor(4.), tensor(1.), tensor(5.), tensor(3.), tensor(2.), tensor(1.)]

In [13]:
pt = list(map(lambda x : float(x),pt))

In [14]:
pt

[4.0, 1.0, 5.0, 3.0, 2.0, 1.0]

In [15]:
points2 = torch.tensor(pt)

In [16]:
points2

tensor([4., 1., 5., 3., 2., 1.])

In [17]:
points == points2

tensor([True, True, True, True, True, True])

In [18]:
float(points[0]) , float(points[1])

(4.0, 1.0)

In [24]:
points = torch.tensor([[4.0,1.0],[1.0,2.0],[3.0,4.0]])

In [20]:
points

tensor([[4., 1.],
        [1., 2.],
        [3., 4.]])

In [21]:
points.shape

torch.Size([3, 2])

In [22]:
points = torch.zeros(3, 2)

In [23]:
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [25]:
points[1,1]

tensor(2.)

In [26]:
points[1][1]

tensor(2.)

In [27]:
points[0]

tensor([4., 1.])

### Named Tensors

In [28]:
img_t = torch.randn(3, 5, 5) # shape[channels, rows, columns]
weights = torch.tensor([0.2123, 0.7152, 0.0722])

In [29]:
batch_t = torch.randn(2, 3, 5, 5) # shape[ batch, channels, rows, columns]
#channles always at index -3
ign = img_t.mean(-3)

In [31]:
bgn = batch_t.mean(-3)

In [33]:
ign.shape, bgn.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [36]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
ig_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

In [37]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [38]:
# Python broadcasting - a form of summarising unnamed things done using three dots "..."
# Not use einsum as follows :

In [39]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [40]:
weights_named = torch.tensor([0.21, 0.71, 0.07], names = ['channels'])
weights_named

C:\Users\divya\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:848.)
  """Entry point for launching an IPython kernel.


tensor([0.2100, 0.7100, 0.0700], names=('channels',))

In [42]:
# If we already have a tensor but want to change / add names :
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("Image Named :",img_named.shape, img_named.names)
print("Batch Named : ", batch_named.shape, batch_named.names)
# Similar to indexing, the ellipsis ... allows us to leave out any number of dimensions

Image Named : torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
Batch Named :  torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [43]:
"""In addition to usual dimension checks- whether sizes are same, or if one is 1 and can be broadcast to another,
PyTorch checks names for us"""

weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [44]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [45]:
gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [46]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

### Managing a Tensor's dtype attributes

In [47]:
double_points = torch.ones(10, 2, dtype = torch.double)
short_points = torch.tensor([[1, 2],[3, 4]], dtype = torch.short)

In [48]:
short_points.dtype

torch.int16

In [49]:
dbl_pts = torch.ones(5,4).double()
shrt_pts = torch.ones(4,2).short()

In [50]:
dbbl_pts = torch.zeros(3,3).to(torch.double)
shhrt_pts = torch.ones(3,3).to(dtype = torch.short)

### Basic methods on tensor objects

In [51]:
a = torch.ones(2, 3)
a_t = torch.transpose(a, 0 ,1)
a.shape, a_t.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [52]:
a_t2 = a.transpose(0, 1)
a.shape, a_t2.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [53]:
points

tensor([[4., 1.],
        [1., 2.],
        [3., 4.]])

In [54]:
points.storage()

 4.0
 1.0
 1.0
 2.0
 3.0
 4.0
[torch.FloatStorage of size 6]

In [55]:
pts_storage = points.storage()
pts_storage[0]

4.0

In [58]:
# Layout of storage is always onedimensional
# Changine value in storage changes the value in corresponding tensor
# Inplace operations are preceeded by _ : example is zero_

In [59]:
a = torch.ones(2, 3)
a.zero_()
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Tensor metadata

In [60]:
# Size , offset and stride are key metadata componenets of a tensor that allow them to index into a storage

In [61]:
points.storage_offset()

0

In [62]:
points

tensor([[4., 1.],
        [1., 2.],
        [3., 4.]])

In [63]:
second_points = points[1]
second_points.storage_offset()

2

In [64]:
second_points.size()

torch.Size([2])

In [65]:
points.stride()

(2, 1)

In [66]:
# Accessing i,j th element in 2D tensor is same as : storage_offset + stride[0]*i + stride[1] * j


In [67]:
second_points.storage_offset()

2

In [69]:
second_points.stride()

(1,)

In [70]:
# since sub tensors affect the original tensor, we clone them into a new tensor
second_point = points[1].clone()

In [71]:
# Transposing withour copying
# the t function is shorthand transpose for 2 dimensional tensors
points

tensor([[4., 1.],
        [1., 2.],
        [3., 4.]])

In [77]:
points_t = points.t()
# USe .transpose() for higher dimesnions

In [73]:
points_t

tensor([[4., 1., 3.],
        [1., 2., 4.]])

In [74]:
id(points.storage()) == id(points_t.storage())

True

In [76]:
print(points.stride())
print(points_t.stride())

(2, 1)
(1, 2)


In [78]:
points.is_contiguous()

True

In [80]:
points_t.is_contiguous()

False

In [81]:
# We obtain a contiguous tensor from a non contiguous tensor using contiguous(), the stride and storage change

In [84]:
points_t.storage()

 4.0
 1.0
 1.0
 2.0
 3.0
 4.0
[torch.FloatStorage of size 6]

In [85]:
points_t.stride()

(1, 2)

In [87]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 1., 3.],
        [1., 2., 4.]])

In [88]:
points_t_cont.stride()

(3, 1)

In [89]:
points_t_cont.storage()

 4.0
 1.0
 3.0
 1.0
 2.0
 4.0
[torch.FloatStorage of size 6]

In [91]:
# Numpy interoperability
points_np = points.numpy()
points_np

array([[4., 1.],
       [1., 2.],
       [3., 4.]], dtype=float32)

In [92]:
points = torch.from_numpy(points_np)

In [93]:
points.dtype

torch.float32

### Serializing Tensors

In [97]:
# Uses Pickle under the hood
torch.save(points,'../PyTorchDiaries/Temp/ourpoints.t')

In [98]:
with open("../PyTorchDiaries/Temp/ourpoints.t","wb") as f :
    torch.save(points,f)

In [99]:
points = torch.load("../PyTorchDiaries/Temp/ourpoints.t")

In [100]:
with open("../PyTorchDiaries/Temp/ourpoints.t","rb") as f :
    points = torch.load(f)

In [101]:
# Interoperability is a concern, but we can use h5py library to serialize to HDF5 format

In [102]:
import h5py

In [104]:
f = h5py.File("../PyTorchDiaries/Temp/ourpoints.hdf5", 'w')
dset = f.create_dataset('coords', data = points.numpy())
f.close()

In [106]:
f = h5py.File("../PyTorchDiaries/Temp/ourpoints.hdf5", 'r')
dset = f['coords']
last_points = dset[-2:]
last_points

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [108]:
last_points = torch.from_numpy(dset[:-2])
f.close()
last_points

tensor([[4., 1.]])